### ISSUE TITLE
Error on update to shopware 6.5

### ISSUE THREAD

**Issue by brontius** [mothership-gmbh/headless-shopware-varnish-cache#4]
We got this Error after update to Shopware 6.5

PHP Fatal error:  Declaration of Mothership\HeadlessShopwareVarnishCacheBundle\HeadlessShopwareVarnishCacheBundle::getContainerExtension() must be compatible with Symfony\Component\HttpKernel\Bundle\Bundle::getContainerExtension(): ?Symfony\Component\DependencyInjection\Extension\ExtensionInterface in /var/www/html/shopware/vendor/mothership/headless-shopware-varnish-cache/HeadlessShopwareVarnishCacheBundle.php on line 10

If you are planning update your extension to be compatible with shopware 6.5 ?

**Comment by niklaswolf** [comment]
Hi, we're defintely planning on supporting 6.5, simply as we want to use it too for our customer projects :) 
I'll have a look at this asap and give some updates.
